name: Touchstone Tests

on:
  push:
    branches:
      - 'develop'
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install .
      - name: Run Touchstone Tests
        working-directory: ./touchstone-tests/touchstone
        run: |
          touchstone run
      - name: Run Java example Touchstone Tests
        working-directory: ./examples/java-spring/touchstone
        run: |
          touchstone run
